#!/usr/bin/env bash

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <input.ipynb> <output.ipynb (relative to input)>" >&2
    exit 1
fi

input="$1"; shift
output="$1"; shift

jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True --output "$output" "$input"
