#!/usr/bin/env bash

set -e

install_kernel=
args=()
for arg in "$@"; do
    if [ "$arg" == "-j" ]; then
        install_kernel=1
    else
        args+=("$arg")
    fi
done

set -- "${args[@]}"

base="${1:-"$(basename "$PWD")"}"
shift || true
version="${1:-${PYTHON_DEFAULT_VERSION}}"
shift || true

echo "$base $version"
name="$base-$version"
pyenv virtualenv "$version" "$name"
pyenv local "$name"
if [ -n "$install_kernel" ]; then
  echo "Installing Jupyter kernel" >&2
  pip install --upgrade pip ipykernel
  install_kernel
else
  echo "Skipping Jupyter kernel install" >&2
fi
