#!/usr/bin/env bash

set -e

install_kernel=
args=()
for arg in "$@"; do
    if [ "$arg" == "-j" ]; then
        install_kernel=1
    else
        args+=("$arg")
    fi
done

set -- "${args[@]}"

base="${1:-"$(basename "$PWD")"}"
shift || true
if [ $# -eq 1 ]; then
    version="$1"; shift
elif [ $# -eq 0 ]; then
    version="$(python --version 2>&1 | grep -o '[0-9.]\+')"
else
    echo "Usage: $0 [-j] [base [version]]" >&2
    exit 1
fi

echo "$base $version"
name="$base-$version"
pyenv virtualenv "$version" "$name"
pyenv local "$name"
if [ -n "$install_kernel" ]; then
  echo "Installing Jupyter kernel" >&2
  pip install --upgrade pip ipykernel
  install_kernel
else
  echo "Skipping Jupyter kernel install" >&2
fi
